system:
  mode: 0 # 0 for graph mode, 1 for pynative mode in MindSpore
  distribute: True
  amp_level: 'O0'
  seed: 42
  log_interval: 200
  val_while_train: True
  drop_overflow_update: False

commom:
  class_path: &class_path ./datasets/XFUND/class_list_xfun.txt
  cache_dir: &cache_dir ./vi_layoutxlm_cache/models/layoutxlm-base-uncased
  max_seq_len: &max_seq_len 512
  num_classes: &num_classes 7

model:
  type: kie
  transform: null
  resume: False
  backbone:
    name: identity
  head:
    name: LayoutXLMForSer
    num_classes: *num_classes

postprocess:
  name: VQASerTokenLayoutLMPostProcess
  class_path: *class_path

metric:
  name: VQASerTokenMetric
  main_indicator: hmean

loss:
  name: VQASerTokenLayoutLMLoss
  num_classes: *num_classes

scheduler:
  scheduler: "polynomial_decay"
  lr: 0.00005
  decay_rate: 1.0
  warmup_epochs: 2
  warmup_factor: 0.0
  decay_epochs: 198
  num_epochs: 200

optimizer:
  opt: adamw
  weight_decay: 0.0

train:
  ema: False
  ema_decay: 0.9999
  clip_grad: True
  clip_norm: 100.0
  ckpt_save_dir: './tmp_vi_layoutxlm'
  dataset_sink_mode: False
  pred_cast_fp32: True
  dataset:
    type: DetDataset
    dataset_root: ./datasets/XFUND # Optional, if set, dataset_root will be used as a prefix for data_dir
    data_dir: zh_train/image
    label_file: zh_train/train.json
    # label_file: # not required when using LMDBDataset
    sample_ratio: 1.0
    shuffle: False
    transform_pipeline:
      - DecodeImage:
          channel_first: False
      - VQATokenLabelEncode: # Class handling label
          cache_dir: *cache_dir
          class_path: *class_path
          contains_re: False
          use_textline_bbox_info: True
          order_method: tb-yx
      - VQATokenPad:
          max_seq_len: *max_seq_len
          return_attention_mask: True
      - VQASerTokenTruncate:
          max_seq_len: *max_seq_len
      - KieResizeImg:
          size: [224, 224]
      - NormalizeImage:
          mean: [123.675, 116.28, 103.53]
          std: [58.395, 57.12, 57.375]
          is_hwc: True
          rgb_to_bgr: True
      - ToCHWImage:

    #  the order of the dataloader list, matching the network input and the input labels for the loss function, and optional data for debug/visaulize
    output_columns: ['image', 'input_ids', 'bbox', 'attention_mask', 'token_type_ids', 'labels']
    net_input_column_index: [0, 1, 2, 3, 4] # input indices for network forward func in output_columns
    label_column_index: [3, 5] # input indices marked as label

  loader:
      shuffle: True # TODO: tbc
      batch_size: 8
      drop_remainder: True
      max_rowsize: 16
      num_workers: 8

eval:
  ckpt_load_path: ./tmp_vi_layoutxlm/best.ckpt
  dataset_sink_mode: False
  pred_cast_fp32: True
  dataset:
    type: DetDataset
    dataset_root: ./datasets/XFUND # Optional, if set, dataset_root will be used as a prefix for data_dir
    data_dir: zh_val/image
    label_file: zh_val/val.json
    # label_file: # not required when using LMDBDataset
    sample_ratio: 1.0
    shuffle: False
    transform_pipeline:
      - DecodeImage:
          channel_first: False
      - VQATokenLabelEncode: # Class handling label
          class_path: *class_path
          cache_dir: *cache_dir
          contains_re: False
          use_textline_bbox_info: True
          order_method: tb-yx
      - VQATokenPad:
          max_seq_len: *max_seq_len
          return_attention_mask: True
      - VQASerTokenTruncate:
          max_seq_len: *max_seq_len
      - KieResizeImg:
          size: [224, 224]
      - NormalizeImage:
          mean: [123.675, 116.28, 103.53]
          std: [58.395, 57.12, 57.375]
          is_hwc: True
          rgb_to_bgr: True
      - ToCHWImage:

    #  the order of the dataloader list, matching the network input and the input labels for the loss function, and optional data for debug/visaulize
    output_columns: ['image', 'input_ids', 'bbox', 'attention_mask', 'token_type_ids', 'labels']
    net_input_column_index: [0, 1, 2, 3, 4] # input indices for network forward func in output_columns
    label_column_index: [3, 5] # input indices marked as label

  loader:
      shuffle: False # TODO: tbc
      batch_size: 1
      drop_remainder: False
      max_rowsize: 16
      num_workers: 8
