# system
mode: 0
distribute: True
num_parallel_workers: 8
val_while_train: True

# dataset
dataset: "imagenet"
data_dir: "/path/to/imagenet"
shuffle: True
dataset_download: False
batch_size: 128
drop_remainder: True

# augmentation
image_resize: 224
scale: [0.08, 1.0]
ratio: [0.75, 1.333]
hflip: 0.5
interpolation: "bilinear"
crop_pct: 0.875
re_prob: 0.25
auto_augment: "randaug-m9-mstd0.5"
aug_repeats: 3

# model
model: "ghostnet_130"
num_classes: 1000
pretrained: False
ckpt_path: ""
keep_checkpoint_max: 30
ckpt_save_dir: "./ckpt"
epoch_size: 600
dataset_sink_mode: True
amp_level: "O3"

# loss
loss: "CE"
label_smoothing: 0.1

# lr scheduler
scheduler: "cosine_decay"
min_lr: 0.0000001
lr: 0.4
warmup_epochs: 20
decay_epochs: 580

# optimizer
opt: "momentum"
filter_bias_and_bn: True
momentum: 0.9
weight_decay: 0.00002
loss_scale_type: "dynamic"
drop_overflow_update: True
loss_scale: 16777216
use_nesterov: False
